<?php
/**
 * @file
 */

/**
 * Implements hook_help().
 */
function caw_helper_help($path, $arg) {
  switch ($path) {
    case 'admin/help#caw':
      return '<p>' . t('Please contact your site administrator') . '</p>';
  }
}

/**
 * Set the bean blocks title to "<none>" if bean has a title and block does not.
 * @param  [type] &$blocks     [description]
 * @param  [type] $theme       [description]
 * @param  [type] $code_blocks [description]
 * @return [type]              [description]
 */
function caw_helper_block_view_alter(&$data, $block) {
  if ($block->module == "bean" && empty($block->title)) {
    $block->title = "<none>";
  }
}

/**
 * Implements hook_init().
 */
function caw_helper_init() {

  $file_path = drupal_get_path('module', 'caw_helper') . "/css/caw_helper.css";
  $conditions[] = "admin";
  $conditions[] = "admin*";
  $conditions[] = "node/*/edit";
  $conditions[] = "block/*/edit*";
  $conditions[] = "block/add*";
  $conditions[] = "node/add*";
  $conditions[] = "user/*/edit";
  $conditions[] = "node/*/delete";

  $css_rules = array();
  $css_rule['rule_conditions'] = $conditions;
  $css_rule['rule_type'] = CSS_INJECTOR_PAGES_NOTLISTED;

  $pass = _css_injector_evaluate_rule($css_rules);
  if ($pass) {
    drupal_add_css($file_path, array('type' => 'file', 'group' => CSS_THEME, 'media' => "all", 'preprocess' => TRUE, 'weight' => 300));
  }

}
